### ISSUE TITLE
Pull request to add server chatwith.xyz

### ISSUE THREAD

**Issue by ahmetsevinc77** [stpeter/xmppdotnet#118]
[vcard-xmpp-chatwith.txt](https://github.com/stpeter/xmppdotnet/files/706251/vcard-xmpp-chatwith.txt)

**Comment by FranklinYu** [comment]
DIY?

**Comment by stpeter** [comment]
From now on, please file pull requests at https://invent.kde.org/melvo/xmpp-providers because I plan to close this repo.
