### ISSUE TITLE
Should this repo/list be deprecated?

### ISSUE THREAD

**Issue by gth4xmpp** [stpeter/xmppdotnet#149]
@stpeter said in #148: 
> Someone in xmpp:[jdev@muc.xmpp.org](mailto:jdev@muc.xmpp.org) pointed me to https://invent.kde.org/melvo/xmpp-providers/-/blob/master/providers.json - apparently that's the list people use these days.

> I'll continue to research this topic. We might want to consolidate lists or deprecate this one.

### Remarks about [invent.kde.org/melvo/xmpp-providers](https://invent.kde.org/melvo/xmpp-providers/) 
Readme.md states that "Usage example: A filtered provider list is primarily used for registering an account with the XMPP client Kaidan." 
And one goal is "Simplifying the onboarding of new XMPP users by a list of XMPP providers that can be integrated into XMPP clients..."
They also say "...providers in this category can be used for an automatic registration." 
What is automatic registration??? 

My point: To do so they reject all providers that do not support In-Band Registration (see their issue list). 
This is a bit prejudiced, I think. (according to [compliance.conversations.im ](https://compliance.conversations.im/test/xep0077/) only about 50% of providers have this enabled). Also we need a human readable list / web representation of it. 

### List of lists of XMPP providers 
For consideration, here are some lists that I came across on a very quick web search. 

- this repo's list [xmpp.net/directory.php](https://xmpp.net/directory.php); #entries: ca. 130; last entry: around 2019?
- [xmpp-servers.404.city](https://xmpp-servers.404.city/); #entries: 155; last entry: october 2021
- [list.jabber.at](https://list.jabber.at/); #entries: ca. 114; last entry: in 2021
- [www.jabberes.org/servers](https://www.jabberes.org/servers/); #entries: >100; last entry: around 2019??; looks very old, lists also offline servers
- [compliance.conversations.im](https://compliance.conversations.im); not really a list, but you can get a list of servers that fullfil one of their checks. E.g. looking for [servers with OMEMO encrypion](https://compliance.conversations.im/test/xep0384/) you see that 91% have this enabled and you get a long list of probably all serves in their db 
- [invent.kde.org/melvo/xmpp-providers](https://invent.kde.org/melvo/xmpp-providers/); #entries: 17 in their providers.json; last entry/edit: oct 2021

### My concern: New users
I write all this because I think about new users, for example people who want to leave WhatsApp and are completely new to the XMPP world. 
I may be wrong, but xmpp.net still appears as one of the first results in a web search. It would be appropiate to have / to keep having some sort of guide there for new users; be it a server listing or sth. else. 
And I think new users would not first install an app (like Kaidan) and let that app suggest them a provider. To my experience new users have a hard time understanding that there is not the ONE app they have to use and that there are also many providers they can choose from. 
So we have to take one step back to catch them, and that's why I think this repo (i.e. the xmpp.net website) is still needed. 
If there should be an up-to-date server list still being kept is of course @stpeter's decision.

**Comment by stpeter** [comment]
Yes, this repo should be deprecated because a team of people has created a new, better, actively-maintained service at https://providers.xmpp.net powered by the repository at https://invent.kde.org/melvo/xmpp-providers
