### ISSUE TITLE
Pull resquest 

### ISSUE THREAD

**Issue by royalterra** [stpeter/xmppdotnet#60]
How long take to be add any pull? is this project a live ?

**Comment by drixter** [comment]
Any update?

**Comment by graffen** [comment]
:+1: on this. Lots of pull requests in the queue :disappointed:

**Comment by Neustradamus** [comment]
http://xmpp.org/extensions/xep-0309.html :)

**Comment by stpeter** [comment]
@tfar and I are working through the backlog now.
