### ISSUE TITLE
Failed to enqueue a test for domain on all tests

### ISSUE THREAD

**Issue by Doemela** [stpeter/xmppdotnet#86]
When trying to test server I allways get "Failed to enqueue a test for "jab.cyberguerrilla.org"."
jab.cyberguerrilla.org runs for couple years nobody has any problem using it.

If I do https://xmpp.net/result.php?domain=jab.cyberguerrilla.org&type=client or &type=server it shows
"Error: Connection failed" but badge is <a href='https://xmpp.net/result.php?domain=jab.cyberguerrilla.org&amp;type=server'><img src='https://xmpp.net/badge.php?domain=jab.cyberguerrilla.org' alt='xmpp.net score' /></a> is this a bug?

**Comment by tfar** [comment]
@xnyhps Any idea? https://xmpp.net/list.php shows no new tests for 22 days.

**Comment by Doemela** [comment]
Test works again but now I get "Error: Connection failed" on both ports those ports are open in my firewall
