### ISSUE TITLE
Not visible on xmpp.net server directory

### ISSUE THREAD

**Issue by drixter** [stpeter/xmppdotnet#89]
Hi,

My server patchcord.be (.xml) was added into git (pull accept), but there is no present on the xmpp.net page, when do you plan to make some sync between github and webpage?

Regards,

**Comment by stpeter** [comment]
We have (had?) a cron job to do that but perhaps it's broken. I'll check into it.

**Comment by drixter** [comment]
How it looks now?

**Comment by tfar** [comment]
@stpeter Had a chance to check into that cron job?

**Comment by drixter** [comment]
@stpeter any update?

**Comment by drixter** [comment]
Any new?

**Comment by owhen** [comment]
any update on this issue?

**Comment by stpeter** [comment]
This issue has been overtaken by events, because https://invent.kde.org/melvo/xmpp-providers is replacing this repository.
